In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

# MNIST is a database of handwritten digits used for training and testing image processing systems and ML algorithms.
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# The pixel values of the images range from 0 through 255. Scale to get a range of 0 to 1
x_train, x_test = x_train / 255.0, x_test / 255.0

# Each layer has one input tensor and one output tensor.
# Layers have a known mathematical structure that can be reused and have trainable variables.
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax') # 10 classes for the ten digits 0-9
])

# Define a loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# configure and compile
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

# fit model parameters to the data / minimize the loss:
model.fit(x_train, y_train, epochs=5)
# evaluate model's performance, on validation set.
model.evaluate(x_test, y_test, verbose=2)

2024-08-24 10:32:59.154066: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-24 10:32:59.203433: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


/home/mz/micromamba/envs/ml/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8636 - loss: 0.4729
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9543 - loss: 0.1553
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9663 - loss: 0.1114
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9728 - loss: 0.0863
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9776 - loss: 0.0728
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9693 - loss: 0.0969


[0.08297765254974365, 0.9733999967575073]

In [2]:
# For each example, the model returns a vector of logits or log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[1.0832801e-11, 1.2580483e-08, 5.9691021e-09, 1.7820671e-02,
        3.1533328e-18, 9.8217922e-01, 2.7335604e-15, 5.5547672e-10,
        4.8505550e-11, 1.0238913e-07]], dtype=float32)

In [16]:
# The tf.nn.softmax function converts these logits to probabilities for each class:
import numpy

# array of probabilities
print(tf.nn.softmax(predictions).numpy())
a = tf.nn.softmax(predictions).numpy()

# max probability and position in the array
a.max(), numpy.argwhere(a.max() == a)

[[0.08555601 0.08555601 0.08555601 0.08709434 0.08555601 0.22845754
  0.08555601 0.08555601 0.08555601 0.08555602]]


(0.22845754, array([[0, 5]]))

In [4]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533861, 0.0853386 , 0.08533863, 0.08534613, 0.0853386 ,
        0.08533864, 0.0853386 , 0.23193997, 0.08533883, 0.08534338],
       [0.08536076, 0.08552364, 0.23158891, 0.08536174, 0.08536076,
        0.08536103, 0.08536076, 0.08536076, 0.08536086, 0.08536076],
       [0.08534589, 0.23182462, 0.08535514, 0.08534651, 0.08534698,
        0.08534651, 0.08534652, 0.08537927, 0.08536269, 0.08534592],
       [0.23191705, 0.08534005, 0.08534096, 0.08534006, 0.08534012,
        0.08534006, 0.08534037, 0.0853461 , 0.08534006, 0.0853551 ],
       [0.08536153, 0.08536142, 0.08536147, 0.08536142, 0.23157856,
        0.08536142, 0.08536146, 0.08536289, 0.08536144, 0.08552845]],
      dtype=float32)>